### ISSUE TITLE
Add CI to interviews.makersacademy.com

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/apply#21]
Standardise the deployments across our repo's

**Comment by ptolemybarnes** [comment]
@nikeshashar Doesn't applications already have CI?

**Comment by nikeshashar** [comment]
@ptolemybarnes Not the interview applications. There's two repo's one private which is apply.makersacademy.com and one public which is the new interviews.makersacademy.com. I'm referring to the latter

**Comment by sjmog** [comment]
This repo is missing large numbers of tests. Until the tests are there, I don't see much sense in adding CI.

**Comment by nikeshashar** [comment]
@sjmog This is preparation for the work to be done to make interviews.makersacademy.com a full project to automate Ronin onboarding

**Comment by sjmog** [comment]
OK. So it's a prototype/spike?

**Comment by sjmog** [comment]
If so, we don't need CI or testing

But we should mention it somewhere in case well-meaning developers get all flouncy about it

**Comment by nikeshashar** [comment]
I believe so. @silvabox has more info on the code status on the project but we can't get full feedback on it working as a standalone product until we get some sort of tracking and front end finalised on it so I can actually test it with real customers without my involvement in guiding them through it.

**Comment by sjmog** [comment]
In this case this needs to get out of the Priority queue until we have proper visibility on this project. I'm trying to pick up tickets to contribute and can't at the moment because I have no idea what to work on.

**Comment by nikeshashar** [comment]
how do I get visibility on the project?
